# Generated by Django 4.2.8 on 2024-05-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('overview', models.TextField(null=True)),
                ('backdrop_path', models.TextField(null=True)),
                ('poster_path', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('adult', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
    ]
