# Generated by Django 4.2.8 on 2024-05-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
