# Generated by Django 4.2.8 on 2024-05-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
